In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [ ]:
torch.manual_seed(1)

In [ ]:
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [ ]:
model = nn.Linear(1, 1)

In [ ]:
print(list(model.parameters()))

In [ ]:
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)

In [ ]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'
            .format(epoch, nb_epochs, cost.item()))

In [ ]:
new_var = torch.FloatTensor([[4.0]])
pred_y = model(new_var)
print("훈련 후 입력이 4일 때의 예측값: ", pred_y)

In [9]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]


In [10]:
import torch
import torch.nn as nn
import torch.nn.functional as F

In [11]:
torch.manual_seed(1)

In [12]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [13]:
model = nn.Linear(3, 1)

In [14]:
print(list(model.parameters()))

[Parameter containing:
tensor([[ 0.2975, -0.2548, -0.1119]], requires_grad=True), Parameter containing:
tensor([0.2710], requires_grad=True)]


In [15]:
optimizer = torch.optim.SGD(model.parameters(), lr=1e-5)

In [16]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):
    prediction = model(x_train)
    cost = F.mse_loss(prediction, y_train)

    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    if epoch%100 == 0:
        print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 31667.597656
Epoch  100/2000 Cost: 0.225988
Epoch  200/2000 Cost: 0.223909
Epoch  300/2000 Cost: 0.221935
Epoch  400/2000 Cost: 0.220059
Epoch  500/2000 Cost: 0.218270
Epoch  600/2000 Cost: 0.216571
Epoch  700/2000 Cost: 0.214954
Epoch  800/2000 Cost: 0.213418
Epoch  900/2000 Cost: 0.211954
Epoch 1000/2000 Cost: 0.210558
Epoch 1100/2000 Cost: 0.209230
Epoch 1200/2000 Cost: 0.207967
Epoch 1300/2000 Cost: 0.206767
Epoch 1400/2000 Cost: 0.205618
Epoch 1500/2000 Cost: 0.204524
Epoch 1600/2000 Cost: 0.203484
Epoch 1700/2000 Cost: 0.202488
Epoch 1800/2000 Cost: 0.201542
Epoch 1900/2000 Cost: 0.200637
Epoch 2000/2000 Cost: 0.199772


In [17]:
new_var = torch.FloatTensor([[73, 80, 75]])
pred_y = model(new_var)
print("훈련 후 입력이 73, 80, 75일 때의 예측값: ", pred_y)

훈련 후 입력이 73, 80, 75일 때의 예측값:  tensor([[151.2305]], grad_fn=<AddmmBackward>)


In [18]:
print(list(model.parameters()))

[Parameter containing:
tensor([[0.9778, 0.4539, 0.5768]], requires_grad=True), Parameter containing:
tensor([0.2802], requires_grad=True)]
