1. Low-Level

In [1]:
import torch
import torch.nn.functional as F

In [2]:
torch.manual_seed(1)

In [3]:
z = torch.FloatTensor([1, 2, 3])

In [4]:
hypothesis = F.softmax(z, dim=0)
print(hypothesis)

tensor([0.0900, 0.2447, 0.6652])


In [5]:
hypothesis.sum()

tensor(1.)

In [6]:
z = torch.randn(3, 5, requires_grad=True)

In [7]:
hypothesis = F.softmax(z, dim=1)
print(hypothesis)

tensor([[0.2847, 0.1919, 0.1563, 0.2735, 0.0935],
        [0.2450, 0.0631, 0.4237, 0.1035, 0.1647],
        [0.1004, 0.2311, 0.2015, 0.0933, 0.3738]], grad_fn=<SoftmaxBackward>)


In [8]:
y = torch.randint(5, (3,)).long()
print(y)

tensor([2, 3, 2])


In [9]:
y_one_hot = torch.zeros_like(hypothesis)
y_one_hot.scatter_(1, y.unsqueeze(1), 1)

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])

In [10]:
print(y_one_hot)

tensor([[0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 1., 0., 0.]])


In [11]:
cost = (y_one_hot * -torch.log(hypothesis)).sum(dim=1).mean()
print(cost)

tensor(1.9087, grad_fn=<MeanBackward0>)


2. High-Level

In [12]:
torch.log(F.softmax(z, dim=1))

tensor([[-1.2563, -1.6507, -1.8559, -1.2963, -2.3695],
        [-1.4066, -2.7632, -0.8588, -2.2680, -1.8035],
        [-2.2989, -1.4648, -1.6021, -2.3722, -0.9842]], grad_fn=<LogBackward>)

In [13]:
F.log_softmax(z, dim=1)

tensor([[-1.2563, -1.6507, -1.8559, -1.2963, -2.3695],
        [-1.4066, -2.7632, -0.8588, -2.2680, -1.8035],
        [-2.2989, -1.4648, -1.6021, -2.3722, -0.9842]],
       grad_fn=<LogSoftmaxBackward>)

In [14]:
(y_one_hot * -torch.log(F.softmax(z, dim=1))).sum(dim=1).mean()

tensor(1.9087, grad_fn=<MeanBackward0>)

In [15]:
(y_one_hot * -F.log_softmax(z, dim=1)).sum(dim=1).mean()

tensor(1.9087, grad_fn=<MeanBackward0>)

In [16]:
F.nll_loss(F.log_softmax(z, dim=1), y)

tensor(1.9087, grad_fn=<NllLossBackward>)

In [17]:
F.cross_entropy(z, y)

tensor(1.9087, grad_fn=<NllLossBackward>)